[gravity]
domain = "gravity"
host = "0.0.0.0"
port = 4222
pingInterval = 10
maxPingsOutstanding = 3
maxReconnects = -1

[adapter]
adapterID = "mysql_adapter"
adapterName = "MySQL Adapter"

[source]
config = "./settings/sources.json"

[store]
enabled = true
path = "./statestore"
